[package]
name = "jarust_make_plugin"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true
doctest = false

[dependencies]
convert_case = "0.6.0"
quote = "1.0.35"
syn = "2.0.46"

[features]
default = ["echotest"]
echotest = []
