[workspace]
resolver = "2"
members = ["jarust", "jarust_plugins", "jarust_rt", "jarust_interface"]

[workspace.package]
version = "0.6.0"
authors = ["Hamza Jadid"]
description = "A janus client SDK in Rust"
readme = "README.md"
license = "Apache-2.0"
keywords = ["janus", "webrtc", "janus-gateway", "async"]
categories = ["network-programming", "asynchronous", "concurrency"]
edition = "2021"
repository = "https://github.com/Ghamza-Jd/jarust"

[workspace.dependencies]
async-trait = "0.1.82"
bytes = "1.7.2"
futures-util = "0.3.30"
log = "0.4.22"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
thiserror = "1.0.63"
tokio = "1.40.0"
tracing = "0.1.40"
