[workspace]
resolver = "2"
members = ["jarust", "jarust_make_plugin", "jarust_plugins"]

[workspace.package]
version = "0.1.5"
authors = ["Hamza Jadid"]
description = "A janus client SDK in Rust"
readme = "README.md"
license = "MIT"
keywords = ["janus", "webrtc", "janus-gateway", "async"]
categories = ["network-programming", "asynchronous", "concurrency"]
edition = "2021"
repository = "https://github.com/Ghamza-Jd/jarust"

[workspace.dependencies]
async-trait = "0.1.77"
log = "0.4.20"
serde = { version = "1.0.195", features = ["derive"] }
serde_json = "1.0.111"
