[workspace]
resolver = "2"
members = ["jarust", "jarust_make_plugin", "jarust_plugins", "client"]

[workspace.dependencies]
async-trait = "0.1.77"
log = "0.4.20"
tokio = { version = "1.35.1", features = ["sync", "time", "rt"] }
tokio-tungstenite = { version = "0.21.0", features = ["native-tls"] }
serde = { version = "1.0.194", features = ["derive"] }
serde_json = "1.0.110"
