[package]
name = "e2e"
version.workspace = true
authors.workspace = true
description.workspace = true
readme.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true
edition.workspace = true
repository.workspace = true
publish = false

[dev-dependencies]
jarust = { version = "0.7.0", path = "../jarust" }
jarust_interface = { version = "0.7.0", path = "../jarust_interface" }
jarust_plugins = { version = "0.7.0", path = "../jarust_plugins" }
tokio = { workspace = true, features = ["time", "macros", "rt-multi-thread"] }
