[package]
name = "jarust_plugins"
version = "0.1.0"
edition = "2021"

[lib]
doctest = false

[dependencies]
async-trait.workspace = true
jarust = { version = "*", path = "../jarust" }
jarust_make_plugin = { version = "*", path = "../jarust_make_plugin" }
log.workspace = true
serde_json.workspace = true
serde.workspace = true
tokio.workspace = true

[features]
default = ["echotest"]
echotest = []
