[package]
name = "jarust_plugins"
version = "0.1.0"
edition = "2021"

[lib]
doctest = false

[dependencies]
async-trait = "0.1.75"
tokio = { version = "1.35.1", features = ["sync", "time", "rt"] }
jarust = { version = "*", path = "../jarust" }
jarust_make_plugin = { version = "*", path = "../jarust_make_plugin" }
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.108"
log = "0.4.20"

[features]
default = ["echotest"]
echotest = []
