[package]
name = "jarust"
version.workspace = true
authors.workspace = true
description.workspace = true
readme.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true
edition.workspace = true
repository.workspace = true

[lib]
doctest = false

[dependencies]
async-trait.workspace = true
futures-util = "0.3.29"
log.workspace = true
rand = "0.8.5"
serde_json.workspace = true
serde.workspace = true
thiserror = "1.0.51"
tokio = { version = "1.35.1", features = ["sync", "time", "rt"] }

[target.'cfg(not(target_family = "wasm"))'.dependencies]
tokio-tungstenite = { version = "0.21.0", features = ["native-tls"] }

[target.'cfg(target_family = "wasm")'.dependencies]
getrandom = { version = "0.2.12", features = ["js"] }

[dev-dependencies]
anyhow = "1.0.79"
simple_logger = "4.3.3"
tokio = { version = "1.35.1", features = ["time", "macros", "rt-multi-thread"] }
