[package]
name = "jarust"
version = "0.1.0"
edition = "2021"

[lib]
doctest = false

[dependencies]
async-trait.workspace = true
futures-util = "0.3.29"
log.workspace = true
rand = "0.8.5"
serde_json.workspace = true
serde.workspace = true
thiserror = "1.0.51"
tokio-tungstenite.workspace = true
tokio.workspace = true

[dev-dependencies]
tokio = { version = "1.35.1", features = ["macros"] }
