[package]
name = "jarust"
version = "0.1.0"
edition = "2021"

[lib]
doctest = false

[dependencies]
async-trait = "0.1.75"
futures-util = "0.3.29"
log = "0.4.20"
rand = "0.8.5"
thiserror = "1.0.51"
tokio = { version = "1.35.1", features = ["sync", "time", "rt"] }
tokio-tungstenite = { version = "0.21.0", features = ["native-tls"] }
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.108"

[dev-dependencies]
tokio = { version = "1.35.1", features = ["macros"] }
