name: Continues Integration

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  clippy:
    name: Clippy check
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo clippy

  test:
    name: Integration test
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo test-core
      - run: cargo test-interface
      - run: cargo test-jarust
      - run: cargo test-plugins

  e2e:
    name: E2E tests
    needs: [test]
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: hoverkraft-tech/compose-action@v2.0.1
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo test-e2e
