name: End-to-End tests

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    name: E2E tests
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4

      - uses: hoverkraft-tech/compose-action@v2.0.1

      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: -p e2e
